server:
  port: 8130 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
aliyun:
  oss:
    endpoint: 你自己的
    keyId: 你自己的
    keySecret: 你自己的
    bucketName: 你自己的